### ISSUE TITLE
command yarn test fails

### ISSUE THREAD

**Issue by iemwill** [Uniswap/merkle-distributor#12]
Hello team!

Like this project and would love to see everything running. Compiling and installing was fine, but `yarn test` gave me the following error which i couldn't resolve until now. 
node -v = v14.17.0
npm -v = 7.17.0
```
/merkle-distributor$ yarn test
yarn run v1.22.10
$ yarn compile
$ rimraf ./build/
$ waffle
$ mocha


  MerkleDistributor
    #token
      1) "before each" hook: deploy token


  0 passing (64ms)
  1 failing

  1) MerkleDistributor
       "before each" hook: deploy token:
     Uncaught Error: Callback was already called.
      at /merkle-distributor/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:36
      at WriteStream.<anonymous> (node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358:17)
      at WriteStream.destroy (node_modules/merkle-patricia-tree/node_modules/level-ws/level-ws.js:140:8)
      at finish (internal/streams/writable.js:670:14)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

/merkle-distributor/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358
                callback(err);
                ^
Error: Callback was already called.
    at /merkle-distributor/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:36
    at WriteStream.<anonymous> (/merkle-distributor/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358:17)
    at WriteStream.emit (events.js:376:20)
    at WriteStream.destroy (/merkle-distributor/node_modules/merkle-patricia-tree/node_modules/level-ws/level-ws.js:140:8)
    at finish (internal/streams/writable.js:670:14)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Brenda-01-01** [comment]
https://docs.github.com/en/github/site-policy/github-community-guidelines#appeal-and-reinstatement

**Comment by Allenwk** [comment]
Has this problem been solved? I also encountered the same problem.

**Comment by iemwill** [comment]
Have you read the https, webAddress. ?

**Comment by manumonti** [comment]
Downgrading to Node v13.9.0 worked for me.
